// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_9m1yVNjAJLNbTDIJVhDdNhlCjkOVvcA',
    appId: '1:953191066647:web:da6d16f81e9b134584c052',
    messagingSenderId: '953191066647',
    projectId: 'alamirat-photo',
    authDomain: 'alamirat-photo.firebaseapp.com',
    storageBucket: 'alamirat-photo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVesLR1oS_kWnnSIOEG0y1U3PjuX9MVVo',
    appId: '1:953191066647:android:0730c6d0c4c0bd4584c052',
    messagingSenderId: '953191066647',
    projectId: 'alamirat-photo',
    storageBucket: 'alamirat-photo.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv-DyFqBZs7MDt90GVrFiLHV_ORIvEfyw',
    appId: '1:953191066647:ios:3022ef86d9f2865884c052',
    messagingSenderId: '953191066647',
    projectId: 'alamirat-photo',
    storageBucket: 'alamirat-photo.firebasestorage.app',
    androidClientId: '953191066647-3vr403777vsapeal3nkapqdul4kibh74.apps.googleusercontent.com',
    iosClientId: '953191066647-og24bora9rhd7jqc0rca3cns28p7hpd9.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_9m1yVNjAJLNbTDIJVhDdNhlCjkOVvcA',
    appId: '1:953191066647:web:cdaa9b87fef1643f84c052',
    messagingSenderId: '953191066647',
    projectId: 'alamirat-photo',
    authDomain: 'alamirat-photo.firebaseapp.com',
    storageBucket: 'alamirat-photo.firebasestorage.app',
  );

}